import { IDiscountProduct, IProduct } from '../Models/inteface';

export const PRODUCTS: IProduct[] = [
  {
    id: 0,
    name: 'Watches',
    currentPrice: 42.0,
    originalPrice: 62.0,
    rating: 2,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'watch1.svg',
    type: 'Tech',
    brand: 'Casio',
    discountOffer: 25,
    category: 'Watches',
  },
  {
    id: 11,
    name: 'Headphones',
    currentPrice: 90.0,
    originalPrice: 99.0,
    rating: 3,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'Head-Point2.svg',
    type: 'Tech',
    brand: 'Sony',
    discountOffer: 20,
    category: 'Headphones',
  },
  {
    id: 1,
    name: 'Watches',
    currentPrice: 42.0,
    originalPrice: 64.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: '/watch2.svg',
    type: 'Tech',
    brand: 'Apple',
    discountOffer: 25,
    category: 'Watches',
  },
  {
    id: 2,
    name: 'Headphones',
    currentPrice: 90.0,
    originalPrice: 99.0,
    rating: 3,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'HeadPoint1.svg',
    type: 'Tech',
    brand: 'Sony',
    discountOffer: 5,
    category: 'Headphones',
  },
  {
    id: 3,
    name: 'Laptop',
    currentPrice: 89.0,
    originalPrice: 99.0,
    rating: 2,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'playstation.svg',
    type: 'Beauty',
    brand: 'Apple',
    discountOffer: 20,
    category: 'Laptop',
  },
  {
    id: 4,
    name: 'MacBook',
    currentPrice: 35.0,
    originalPrice: 55.0,
    rating: 5,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'MacBook.svg',
    type: 'Fashion',
    brand: 'Casio',
    discountOffer: 5,
    category: 'Laptop',
  },
  {
    id: 5,
    name: 'Game console',
    currentPrice: 76.0,
    originalPrice: 89.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'playstation.svg',
    type: 'Tech',
    brand: 'Sony',
    discountOffer: 25,
    category: 'Game Console',
  },
  {
    id: 6,
    name: 'Shoes',
    currentPrice: 57.0,
    originalPrice: 75.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'shoes1.svg',
    type: 'Trend',
    brand: 'Nike',
    discountOffer: 20,
    category: 'Clothe',
  },
  {
    id: 7,
    name: 'Chaire',
    currentPrice: 39,
    originalPrice: 60,
    rating: 5,
    description: 'Unique Features Of leatest & Trending Poducts',
    url: 'Chaire-blue.svg',
    type: 'Home',
    brand: 'Glassiness',
    discountOffer: 5,
    category: 'Jewellery',
  },
  {
    id: 8,
    name: 'Game console',
    currentPrice: 76.0,
    originalPrice: 89.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'playstation.svg',
    type: 'Trend',
    brand: 'Sony',
    discountOffer: 25,
    category: 'Game Console',
  },
  {
    id: 9,
    name: 'Game console',
    currentPrice: 76.0,
    originalPrice: 89.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'playstation.svg',
    type: 'Trend',
    brand: 'Sony',
    discountOffer: 25,
    category: 'Game Console',
  },
  {
    id: 10,
    name: 'Headphones',
    currentPrice: 90.0,
    originalPrice: 99.0,
    rating: 3,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'HeadPoint1.svg',
    type: 'Tech',
    brand: 'Sony',
    discountOffer: 20,
    category: 'Headphones',
  },
  {
    _id: 1,
    id: 11,
    name: 'Ring',
    currentPrice: 42.0,
    originalPrice: 62.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'Ring.svg',
    type: 'Trend',
    brand: 'Vke',
    discountOffer: 5,
    category: 'Jewellery',
  },
  {
    name: 'Present-box',
    id: 12,
    currentPrice: 42.0,
    originalPrice: 62.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'present-box.svg',
    type: 'Tech',
    brand: 'Apple',
    discountOffer: 5,
    category: 'Other',
  },
  {
    id: 13,
    name: 'Braslet',
    currentPrice: 42.0,
    originalPrice: 62.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'braslet.svg',
    type: 'Tech',
    brand: 'Apple',
    discountOffer: 20,
    category: 'Jewellery',
  },
  {
    id: 14,
    _id: 1,
    owner: 'Jon Doe',
    date: new Date('2023-08-21'),
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec hendrerit hendrerit ex.',
    url: 'Home-trand1.svg',
    type: 'Home',
    rating: 5,
    name: 'Home',
    title: 'Top essential Trends in 2023',
    currentPrice: 211,
    originalPrice: 232,
    brand: 'Glassiness',
    discountOffer: 25,
    category: 'Other',
  },
  {
    id: 15,
    owner: 'Jon Doe',
    date: new Date('2023-08-21'),
    description:
      'Nullam nec fringilla erat, ac dapibus nunc. Integer semper ipsum in fermentum aliquam.',
    url: 'Home-trand2.svg',
    type: 'Home',
    rating: 5,
    name: 'Home',
    title: 'Top essential Trends in 2023',
    currentPrice: 211,
    originalPrice: 232,
    brand: 'Glassiness',
    discountOffer: 25,
    category: 'Other',
  },
  {
    _id: 3,
    id: 16,
    owner: 'Jon Doe',
    date: new Date('2023-08-21'),
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec hendrerit hendrerit ex.',
    url: 'home-trand3.svg',
    type: 'Home',
    rating: 5,
    name: 'Home',
    title: 'Top essential Trends in 2023',
    currentPrice: 211,
    originalPrice: 232,
    brand: 'Glassiness',
    discountOffer: 25,
    category: 'Other',
  },
];

export const DISCOUNT_PRODUCTS: IDiscountProduct[] = [
  {
    _id: 3,
    smallTitle: 'Ultimate Gaming Experience',
    title: 'Next-Gen Gaming \n Control Systems',
    paragraph:
      'Take your gaming to the next level with high-precision controllers and lightning-fast response times.',
    imgUrl: 'playstation.svg',
    id: 8,
    type: 'LapTop',
  },
  {
    _id: 1,
    smallTitle: 'Premium Home Furniture Collection',
    title: 'Elegant Blue Velvet \n Accent Chairs',
    paragraph:
      'Enhance your living space with our latest ergonomic designs. Crafted for comfort and styled for the modern home.',
    imgUrl: 'Chaire-blue.svg',
    id: 7,
    type: 'Other',
  },
  {
    _id: 2,
    title: 'New Trendy Collection Headphones',
    smallTitle: 'Headphones Compact',
    paragraph:
      'Experience immersive sound quality and noise cancellation. Perfect for music lovers and professionals alike.',
    imgUrl: 'hero-HeadPoint.svg',
    id: 2,
    type: 'HeadPhone',
  },
];

export const TOP_CATEGORIES: IProduct[] = [
  {
    _id: 0,
    id: 0,
    name: 'Perfum',
    currentPrice: 42.0,
    originalPrice: 62.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'Perfume1.svg',
    type: 'Fashion',
  },
  {
    _id: 1,
    id: 11,
    name: 'Ring',
    currentPrice: 42.0,
    originalPrice: 62.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'Ring.svg',
    type: 'Trend',
  },
  {
    _id: 2,
    name: 'present-box',
    id: 12,
    currentPrice: 42.0,
    originalPrice: 62.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'present-box.svg',
    type: 'Tech',
  },
  {
    _id: 3,
    id: 13,
    name: 'Braslet',
    currentPrice: 42.0,
    originalPrice: 62.0,
    rating: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.',
    url: 'braslet.svg',
    type: 'Tech',
  },
];

export const HOMES: IProduct[] = [
  {
    id: 14,
    _id: 1,
    owner: 'Jon Doe',
    date: new Date('2023-08-21'),
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec hendrerit hendrerit ex.',
    url: 'Home-trand1.svg',
    type: 'Home',
    rating: 5,
    name: 'Home',
    title: 'Top essential Trends in 2023',
    currentPrice: 211,
    originalPrice: 232,
  },
  {
    _id: 2,
    id: 15,
    owner: 'Jon Doe',
    date: new Date('2023-08-21'),
    description:
      'Nullam nec fringilla erat, ac dapibus nunc. Integer semper ipsum in fermentum aliquam. ',
    url: 'Home-trand2.svg',
    type: 'Home',
    rating: 5,
    name: 'Home',
    title: 'Top essential Trends in 2023',
    currentPrice: 211,
    originalPrice: 232,
  },
  {
    _id: 3,
    id: 16,
    owner: 'Jon Doe',
    date: new Date('2023-08-21'),
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec hendrerit hendrerit ex.',
    url: 'home-trand3.svg',
    type: 'Home',
    rating: 5,
    name: 'Home',
    title: 'Top essential Trends in 2023',
    currentPrice: 211,
    originalPrice: 232,
  },
];
